// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartLighting.proto

package com.smart_home;

public final class SmartLightingOuterClass {
  private SmartLightingOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ToggleLightRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ToggleLightRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string light_id = 1;</code>
     */
    java.lang.String getLightId();
    /**
     * <code>string light_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getLightIdBytes();

    /**
     * <code>bool intended_state = 2;</code>
     */
    boolean getIntendedState();
  }
  /**
   * <pre>
   *Unary RPC method toggles the state of a single light or a set of lights.
   * </pre>
   *
   * Protobuf type {@code ToggleLightRequest}
   */
  public  static final class ToggleLightRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ToggleLightRequest)
      ToggleLightRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ToggleLightRequest.newBuilder() to construct.
    private ToggleLightRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ToggleLightRequest() {
      lightId_ = "";
      intendedState_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ToggleLightRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              lightId_ = s;
              break;
            }
            case 16: {

              intendedState_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.smart_home.SmartLightingOuterClass.internal_static_ToggleLightRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.smart_home.SmartLightingOuterClass.internal_static_ToggleLightRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.smart_home.SmartLightingOuterClass.ToggleLightRequest.class, com.smart_home.SmartLightingOuterClass.ToggleLightRequest.Builder.class);
    }

    public static final int LIGHT_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object lightId_;
    /**
     * <code>string light_id = 1;</code>
     */
    public java.lang.String getLightId() {
      java.lang.Object ref = lightId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lightId_ = s;
        return s;
      }
    }
    /**
     * <code>string light_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLightIdBytes() {
      java.lang.Object ref = lightId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lightId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INTENDED_STATE_FIELD_NUMBER = 2;
    private boolean intendedState_;
    /**
     * <code>bool intended_state = 2;</code>
     */
    public boolean getIntendedState() {
      return intendedState_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getLightIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, lightId_);
      }
      if (intendedState_ != false) {
        output.writeBool(2, intendedState_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getLightIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, lightId_);
      }
      if (intendedState_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, intendedState_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.smart_home.SmartLightingOuterClass.ToggleLightRequest)) {
        return super.equals(obj);
      }
      com.smart_home.SmartLightingOuterClass.ToggleLightRequest other = (com.smart_home.SmartLightingOuterClass.ToggleLightRequest) obj;

      boolean result = true;
      result = result && getLightId()
          .equals(other.getLightId());
      result = result && (getIntendedState()
          == other.getIntendedState());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LIGHT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getLightId().hashCode();
      hash = (37 * hash) + INTENDED_STATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIntendedState());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.smart_home.SmartLightingOuterClass.ToggleLightRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smart_home.SmartLightingOuterClass.ToggleLightRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smart_home.SmartLightingOuterClass.ToggleLightRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smart_home.SmartLightingOuterClass.ToggleLightRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smart_home.SmartLightingOuterClass.ToggleLightRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smart_home.SmartLightingOuterClass.ToggleLightRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smart_home.SmartLightingOuterClass.ToggleLightRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.smart_home.SmartLightingOuterClass.ToggleLightRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.smart_home.SmartLightingOuterClass.ToggleLightRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.smart_home.SmartLightingOuterClass.ToggleLightRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.smart_home.SmartLightingOuterClass.ToggleLightRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.smart_home.SmartLightingOuterClass.ToggleLightRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.smart_home.SmartLightingOuterClass.ToggleLightRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *Unary RPC method toggles the state of a single light or a set of lights.
     * </pre>
     *
     * Protobuf type {@code ToggleLightRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ToggleLightRequest)
        com.smart_home.SmartLightingOuterClass.ToggleLightRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.smart_home.SmartLightingOuterClass.internal_static_ToggleLightRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.smart_home.SmartLightingOuterClass.internal_static_ToggleLightRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.smart_home.SmartLightingOuterClass.ToggleLightRequest.class, com.smart_home.SmartLightingOuterClass.ToggleLightRequest.Builder.class);
      }

      // Construct using com.smart_home.SmartLightingOuterClass.ToggleLightRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        lightId_ = "";

        intendedState_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.smart_home.SmartLightingOuterClass.internal_static_ToggleLightRequest_descriptor;
      }

      @java.lang.Override
      public com.smart_home.SmartLightingOuterClass.ToggleLightRequest getDefaultInstanceForType() {
        return com.smart_home.SmartLightingOuterClass.ToggleLightRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.smart_home.SmartLightingOuterClass.ToggleLightRequest build() {
        com.smart_home.SmartLightingOuterClass.ToggleLightRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.smart_home.SmartLightingOuterClass.ToggleLightRequest buildPartial() {
        com.smart_home.SmartLightingOuterClass.ToggleLightRequest result = new com.smart_home.SmartLightingOuterClass.ToggleLightRequest(this);
        result.lightId_ = lightId_;
        result.intendedState_ = intendedState_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.smart_home.SmartLightingOuterClass.ToggleLightRequest) {
          return mergeFrom((com.smart_home.SmartLightingOuterClass.ToggleLightRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.smart_home.SmartLightingOuterClass.ToggleLightRequest other) {
        if (other == com.smart_home.SmartLightingOuterClass.ToggleLightRequest.getDefaultInstance()) return this;
        if (!other.getLightId().isEmpty()) {
          lightId_ = other.lightId_;
          onChanged();
        }
        if (other.getIntendedState() != false) {
          setIntendedState(other.getIntendedState());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.smart_home.SmartLightingOuterClass.ToggleLightRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.smart_home.SmartLightingOuterClass.ToggleLightRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object lightId_ = "";
      /**
       * <code>string light_id = 1;</code>
       */
      public java.lang.String getLightId() {
        java.lang.Object ref = lightId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lightId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string light_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLightIdBytes() {
        java.lang.Object ref = lightId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lightId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string light_id = 1;</code>
       */
      public Builder setLightId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lightId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string light_id = 1;</code>
       */
      public Builder clearLightId() {
        
        lightId_ = getDefaultInstance().getLightId();
        onChanged();
        return this;
      }
      /**
       * <code>string light_id = 1;</code>
       */
      public Builder setLightIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lightId_ = value;
        onChanged();
        return this;
      }

      private boolean intendedState_ ;
      /**
       * <code>bool intended_state = 2;</code>
       */
      public boolean getIntendedState() {
        return intendedState_;
      }
      /**
       * <code>bool intended_state = 2;</code>
       */
      public Builder setIntendedState(boolean value) {
        
        intendedState_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool intended_state = 2;</code>
       */
      public Builder clearIntendedState() {
        
        intendedState_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ToggleLightRequest)
    }

    // @@protoc_insertion_point(class_scope:ToggleLightRequest)
    private static final com.smart_home.SmartLightingOuterClass.ToggleLightRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.smart_home.SmartLightingOuterClass.ToggleLightRequest();
    }

    public static com.smart_home.SmartLightingOuterClass.ToggleLightRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ToggleLightRequest>
        PARSER = new com.google.protobuf.AbstractParser<ToggleLightRequest>() {
      @java.lang.Override
      public ToggleLightRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ToggleLightRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ToggleLightRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ToggleLightRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.smart_home.SmartLightingOuterClass.ToggleLightRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ToggleLightResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ToggleLightResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool success = 1;</code>
     */
    boolean getSuccess();
  }
  /**
   * Protobuf type {@code ToggleLightResponse}
   */
  public  static final class ToggleLightResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ToggleLightResponse)
      ToggleLightResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ToggleLightResponse.newBuilder() to construct.
    private ToggleLightResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ToggleLightResponse() {
      success_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ToggleLightResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              success_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.smart_home.SmartLightingOuterClass.internal_static_ToggleLightResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.smart_home.SmartLightingOuterClass.internal_static_ToggleLightResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.smart_home.SmartLightingOuterClass.ToggleLightResponse.class, com.smart_home.SmartLightingOuterClass.ToggleLightResponse.Builder.class);
    }

    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>bool success = 1;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (success_ != false) {
        output.writeBool(1, success_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.smart_home.SmartLightingOuterClass.ToggleLightResponse)) {
        return super.equals(obj);
      }
      com.smart_home.SmartLightingOuterClass.ToggleLightResponse other = (com.smart_home.SmartLightingOuterClass.ToggleLightResponse) obj;

      boolean result = true;
      result = result && (getSuccess()
          == other.getSuccess());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.smart_home.SmartLightingOuterClass.ToggleLightResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smart_home.SmartLightingOuterClass.ToggleLightResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smart_home.SmartLightingOuterClass.ToggleLightResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smart_home.SmartLightingOuterClass.ToggleLightResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smart_home.SmartLightingOuterClass.ToggleLightResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smart_home.SmartLightingOuterClass.ToggleLightResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smart_home.SmartLightingOuterClass.ToggleLightResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.smart_home.SmartLightingOuterClass.ToggleLightResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.smart_home.SmartLightingOuterClass.ToggleLightResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.smart_home.SmartLightingOuterClass.ToggleLightResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.smart_home.SmartLightingOuterClass.ToggleLightResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.smart_home.SmartLightingOuterClass.ToggleLightResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.smart_home.SmartLightingOuterClass.ToggleLightResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ToggleLightResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ToggleLightResponse)
        com.smart_home.SmartLightingOuterClass.ToggleLightResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.smart_home.SmartLightingOuterClass.internal_static_ToggleLightResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.smart_home.SmartLightingOuterClass.internal_static_ToggleLightResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.smart_home.SmartLightingOuterClass.ToggleLightResponse.class, com.smart_home.SmartLightingOuterClass.ToggleLightResponse.Builder.class);
      }

      // Construct using com.smart_home.SmartLightingOuterClass.ToggleLightResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        success_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.smart_home.SmartLightingOuterClass.internal_static_ToggleLightResponse_descriptor;
      }

      @java.lang.Override
      public com.smart_home.SmartLightingOuterClass.ToggleLightResponse getDefaultInstanceForType() {
        return com.smart_home.SmartLightingOuterClass.ToggleLightResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.smart_home.SmartLightingOuterClass.ToggleLightResponse build() {
        com.smart_home.SmartLightingOuterClass.ToggleLightResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.smart_home.SmartLightingOuterClass.ToggleLightResponse buildPartial() {
        com.smart_home.SmartLightingOuterClass.ToggleLightResponse result = new com.smart_home.SmartLightingOuterClass.ToggleLightResponse(this);
        result.success_ = success_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.smart_home.SmartLightingOuterClass.ToggleLightResponse) {
          return mergeFrom((com.smart_home.SmartLightingOuterClass.ToggleLightResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.smart_home.SmartLightingOuterClass.ToggleLightResponse other) {
        if (other == com.smart_home.SmartLightingOuterClass.ToggleLightResponse.getDefaultInstance()) return this;
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.smart_home.SmartLightingOuterClass.ToggleLightResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.smart_home.SmartLightingOuterClass.ToggleLightResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean success_ ;
      /**
       * <code>bool success = 1;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>bool success = 1;</code>
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool success = 1;</code>
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ToggleLightResponse)
    }

    // @@protoc_insertion_point(class_scope:ToggleLightResponse)
    private static final com.smart_home.SmartLightingOuterClass.ToggleLightResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.smart_home.SmartLightingOuterClass.ToggleLightResponse();
    }

    public static com.smart_home.SmartLightingOuterClass.ToggleLightResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ToggleLightResponse>
        PARSER = new com.google.protobuf.AbstractParser<ToggleLightResponse>() {
      @java.lang.Override
      public ToggleLightResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ToggleLightResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ToggleLightResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ToggleLightResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.smart_home.SmartLightingOuterClass.ToggleLightResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SetScheduleRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SetScheduleRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string light_id = 1;</code>
     */
    java.lang.String getLightId();
    /**
     * <code>string light_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getLightIdBytes();

    /**
     * <code>bool intended_state = 2;</code>
     */
    boolean getIntendedState();

    /**
     * <code>string schedule_time = 3;</code>
     */
    java.lang.String getScheduleTime();
    /**
     * <code>string schedule_time = 3;</code>
     */
    com.google.protobuf.ByteString
        getScheduleTimeBytes();
  }
  /**
   * <pre>
   *This is a client streaming RPC method, user can programme when the lights will turn on and off.
   * </pre>
   *
   * Protobuf type {@code SetScheduleRequest}
   */
  public  static final class SetScheduleRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SetScheduleRequest)
      SetScheduleRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SetScheduleRequest.newBuilder() to construct.
    private SetScheduleRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SetScheduleRequest() {
      lightId_ = "";
      intendedState_ = false;
      scheduleTime_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SetScheduleRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              lightId_ = s;
              break;
            }
            case 16: {

              intendedState_ = input.readBool();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              scheduleTime_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.smart_home.SmartLightingOuterClass.internal_static_SetScheduleRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.smart_home.SmartLightingOuterClass.internal_static_SetScheduleRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.smart_home.SmartLightingOuterClass.SetScheduleRequest.class, com.smart_home.SmartLightingOuterClass.SetScheduleRequest.Builder.class);
    }

    public static final int LIGHT_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object lightId_;
    /**
     * <code>string light_id = 1;</code>
     */
    public java.lang.String getLightId() {
      java.lang.Object ref = lightId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lightId_ = s;
        return s;
      }
    }
    /**
     * <code>string light_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLightIdBytes() {
      java.lang.Object ref = lightId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lightId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INTENDED_STATE_FIELD_NUMBER = 2;
    private boolean intendedState_;
    /**
     * <code>bool intended_state = 2;</code>
     */
    public boolean getIntendedState() {
      return intendedState_;
    }

    public static final int SCHEDULE_TIME_FIELD_NUMBER = 3;
    private volatile java.lang.Object scheduleTime_;
    /**
     * <code>string schedule_time = 3;</code>
     */
    public java.lang.String getScheduleTime() {
      java.lang.Object ref = scheduleTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        scheduleTime_ = s;
        return s;
      }
    }
    /**
     * <code>string schedule_time = 3;</code>
     */
    public com.google.protobuf.ByteString
        getScheduleTimeBytes() {
      java.lang.Object ref = scheduleTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        scheduleTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getLightIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, lightId_);
      }
      if (intendedState_ != false) {
        output.writeBool(2, intendedState_);
      }
      if (!getScheduleTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, scheduleTime_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getLightIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, lightId_);
      }
      if (intendedState_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, intendedState_);
      }
      if (!getScheduleTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, scheduleTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.smart_home.SmartLightingOuterClass.SetScheduleRequest)) {
        return super.equals(obj);
      }
      com.smart_home.SmartLightingOuterClass.SetScheduleRequest other = (com.smart_home.SmartLightingOuterClass.SetScheduleRequest) obj;

      boolean result = true;
      result = result && getLightId()
          .equals(other.getLightId());
      result = result && (getIntendedState()
          == other.getIntendedState());
      result = result && getScheduleTime()
          .equals(other.getScheduleTime());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LIGHT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getLightId().hashCode();
      hash = (37 * hash) + INTENDED_STATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIntendedState());
      hash = (37 * hash) + SCHEDULE_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getScheduleTime().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.smart_home.SmartLightingOuterClass.SetScheduleRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smart_home.SmartLightingOuterClass.SetScheduleRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smart_home.SmartLightingOuterClass.SetScheduleRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smart_home.SmartLightingOuterClass.SetScheduleRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smart_home.SmartLightingOuterClass.SetScheduleRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smart_home.SmartLightingOuterClass.SetScheduleRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smart_home.SmartLightingOuterClass.SetScheduleRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.smart_home.SmartLightingOuterClass.SetScheduleRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.smart_home.SmartLightingOuterClass.SetScheduleRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.smart_home.SmartLightingOuterClass.SetScheduleRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.smart_home.SmartLightingOuterClass.SetScheduleRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.smart_home.SmartLightingOuterClass.SetScheduleRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.smart_home.SmartLightingOuterClass.SetScheduleRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *This is a client streaming RPC method, user can programme when the lights will turn on and off.
     * </pre>
     *
     * Protobuf type {@code SetScheduleRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SetScheduleRequest)
        com.smart_home.SmartLightingOuterClass.SetScheduleRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.smart_home.SmartLightingOuterClass.internal_static_SetScheduleRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.smart_home.SmartLightingOuterClass.internal_static_SetScheduleRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.smart_home.SmartLightingOuterClass.SetScheduleRequest.class, com.smart_home.SmartLightingOuterClass.SetScheduleRequest.Builder.class);
      }

      // Construct using com.smart_home.SmartLightingOuterClass.SetScheduleRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        lightId_ = "";

        intendedState_ = false;

        scheduleTime_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.smart_home.SmartLightingOuterClass.internal_static_SetScheduleRequest_descriptor;
      }

      @java.lang.Override
      public com.smart_home.SmartLightingOuterClass.SetScheduleRequest getDefaultInstanceForType() {
        return com.smart_home.SmartLightingOuterClass.SetScheduleRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.smart_home.SmartLightingOuterClass.SetScheduleRequest build() {
        com.smart_home.SmartLightingOuterClass.SetScheduleRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.smart_home.SmartLightingOuterClass.SetScheduleRequest buildPartial() {
        com.smart_home.SmartLightingOuterClass.SetScheduleRequest result = new com.smart_home.SmartLightingOuterClass.SetScheduleRequest(this);
        result.lightId_ = lightId_;
        result.intendedState_ = intendedState_;
        result.scheduleTime_ = scheduleTime_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.smart_home.SmartLightingOuterClass.SetScheduleRequest) {
          return mergeFrom((com.smart_home.SmartLightingOuterClass.SetScheduleRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.smart_home.SmartLightingOuterClass.SetScheduleRequest other) {
        if (other == com.smart_home.SmartLightingOuterClass.SetScheduleRequest.getDefaultInstance()) return this;
        if (!other.getLightId().isEmpty()) {
          lightId_ = other.lightId_;
          onChanged();
        }
        if (other.getIntendedState() != false) {
          setIntendedState(other.getIntendedState());
        }
        if (!other.getScheduleTime().isEmpty()) {
          scheduleTime_ = other.scheduleTime_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.smart_home.SmartLightingOuterClass.SetScheduleRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.smart_home.SmartLightingOuterClass.SetScheduleRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object lightId_ = "";
      /**
       * <code>string light_id = 1;</code>
       */
      public java.lang.String getLightId() {
        java.lang.Object ref = lightId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lightId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string light_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLightIdBytes() {
        java.lang.Object ref = lightId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lightId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string light_id = 1;</code>
       */
      public Builder setLightId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lightId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string light_id = 1;</code>
       */
      public Builder clearLightId() {
        
        lightId_ = getDefaultInstance().getLightId();
        onChanged();
        return this;
      }
      /**
       * <code>string light_id = 1;</code>
       */
      public Builder setLightIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lightId_ = value;
        onChanged();
        return this;
      }

      private boolean intendedState_ ;
      /**
       * <code>bool intended_state = 2;</code>
       */
      public boolean getIntendedState() {
        return intendedState_;
      }
      /**
       * <code>bool intended_state = 2;</code>
       */
      public Builder setIntendedState(boolean value) {
        
        intendedState_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool intended_state = 2;</code>
       */
      public Builder clearIntendedState() {
        
        intendedState_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object scheduleTime_ = "";
      /**
       * <code>string schedule_time = 3;</code>
       */
      public java.lang.String getScheduleTime() {
        java.lang.Object ref = scheduleTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          scheduleTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string schedule_time = 3;</code>
       */
      public com.google.protobuf.ByteString
          getScheduleTimeBytes() {
        java.lang.Object ref = scheduleTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          scheduleTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string schedule_time = 3;</code>
       */
      public Builder setScheduleTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        scheduleTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string schedule_time = 3;</code>
       */
      public Builder clearScheduleTime() {
        
        scheduleTime_ = getDefaultInstance().getScheduleTime();
        onChanged();
        return this;
      }
      /**
       * <code>string schedule_time = 3;</code>
       */
      public Builder setScheduleTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        scheduleTime_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SetScheduleRequest)
    }

    // @@protoc_insertion_point(class_scope:SetScheduleRequest)
    private static final com.smart_home.SmartLightingOuterClass.SetScheduleRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.smart_home.SmartLightingOuterClass.SetScheduleRequest();
    }

    public static com.smart_home.SmartLightingOuterClass.SetScheduleRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SetScheduleRequest>
        PARSER = new com.google.protobuf.AbstractParser<SetScheduleRequest>() {
      @java.lang.Override
      public SetScheduleRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SetScheduleRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SetScheduleRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SetScheduleRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.smart_home.SmartLightingOuterClass.SetScheduleRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SetScheduleResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SetScheduleResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool success = 1;</code>
     */
    boolean getSuccess();
  }
  /**
   * Protobuf type {@code SetScheduleResponse}
   */
  public  static final class SetScheduleResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SetScheduleResponse)
      SetScheduleResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SetScheduleResponse.newBuilder() to construct.
    private SetScheduleResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SetScheduleResponse() {
      success_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SetScheduleResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              success_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.smart_home.SmartLightingOuterClass.internal_static_SetScheduleResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.smart_home.SmartLightingOuterClass.internal_static_SetScheduleResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.smart_home.SmartLightingOuterClass.SetScheduleResponse.class, com.smart_home.SmartLightingOuterClass.SetScheduleResponse.Builder.class);
    }

    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>bool success = 1;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (success_ != false) {
        output.writeBool(1, success_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.smart_home.SmartLightingOuterClass.SetScheduleResponse)) {
        return super.equals(obj);
      }
      com.smart_home.SmartLightingOuterClass.SetScheduleResponse other = (com.smart_home.SmartLightingOuterClass.SetScheduleResponse) obj;

      boolean result = true;
      result = result && (getSuccess()
          == other.getSuccess());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.smart_home.SmartLightingOuterClass.SetScheduleResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smart_home.SmartLightingOuterClass.SetScheduleResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smart_home.SmartLightingOuterClass.SetScheduleResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smart_home.SmartLightingOuterClass.SetScheduleResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smart_home.SmartLightingOuterClass.SetScheduleResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smart_home.SmartLightingOuterClass.SetScheduleResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smart_home.SmartLightingOuterClass.SetScheduleResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.smart_home.SmartLightingOuterClass.SetScheduleResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.smart_home.SmartLightingOuterClass.SetScheduleResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.smart_home.SmartLightingOuterClass.SetScheduleResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.smart_home.SmartLightingOuterClass.SetScheduleResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.smart_home.SmartLightingOuterClass.SetScheduleResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.smart_home.SmartLightingOuterClass.SetScheduleResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SetScheduleResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SetScheduleResponse)
        com.smart_home.SmartLightingOuterClass.SetScheduleResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.smart_home.SmartLightingOuterClass.internal_static_SetScheduleResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.smart_home.SmartLightingOuterClass.internal_static_SetScheduleResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.smart_home.SmartLightingOuterClass.SetScheduleResponse.class, com.smart_home.SmartLightingOuterClass.SetScheduleResponse.Builder.class);
      }

      // Construct using com.smart_home.SmartLightingOuterClass.SetScheduleResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        success_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.smart_home.SmartLightingOuterClass.internal_static_SetScheduleResponse_descriptor;
      }

      @java.lang.Override
      public com.smart_home.SmartLightingOuterClass.SetScheduleResponse getDefaultInstanceForType() {
        return com.smart_home.SmartLightingOuterClass.SetScheduleResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.smart_home.SmartLightingOuterClass.SetScheduleResponse build() {
        com.smart_home.SmartLightingOuterClass.SetScheduleResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.smart_home.SmartLightingOuterClass.SetScheduleResponse buildPartial() {
        com.smart_home.SmartLightingOuterClass.SetScheduleResponse result = new com.smart_home.SmartLightingOuterClass.SetScheduleResponse(this);
        result.success_ = success_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.smart_home.SmartLightingOuterClass.SetScheduleResponse) {
          return mergeFrom((com.smart_home.SmartLightingOuterClass.SetScheduleResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.smart_home.SmartLightingOuterClass.SetScheduleResponse other) {
        if (other == com.smart_home.SmartLightingOuterClass.SetScheduleResponse.getDefaultInstance()) return this;
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.smart_home.SmartLightingOuterClass.SetScheduleResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.smart_home.SmartLightingOuterClass.SetScheduleResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean success_ ;
      /**
       * <code>bool success = 1;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>bool success = 1;</code>
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool success = 1;</code>
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SetScheduleResponse)
    }

    // @@protoc_insertion_point(class_scope:SetScheduleResponse)
    private static final com.smart_home.SmartLightingOuterClass.SetScheduleResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.smart_home.SmartLightingOuterClass.SetScheduleResponse();
    }

    public static com.smart_home.SmartLightingOuterClass.SetScheduleResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SetScheduleResponse>
        PARSER = new com.google.protobuf.AbstractParser<SetScheduleResponse>() {
      @java.lang.Override
      public SetScheduleResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SetScheduleResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SetScheduleResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SetScheduleResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.smart_home.SmartLightingOuterClass.SetScheduleResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ToggleLightRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ToggleLightRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ToggleLightResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ToggleLightResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SetScheduleRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SetScheduleRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SetScheduleResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SetScheduleResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023SmartLighting.proto\">\n\022ToggleLightRequ" +
      "est\022\020\n\010light_id\030\001 \001(\t\022\026\n\016intended_state\030" +
      "\002 \001(\010\"&\n\023ToggleLightResponse\022\017\n\007success\030" +
      "\001 \001(\010\"U\n\022SetScheduleRequest\022\020\n\010light_id\030" +
      "\001 \001(\t\022\026\n\016intended_state\030\002 \001(\010\022\025\n\rschedul" +
      "e_time\030\003 \001(\t\"&\n\023SetScheduleResponse\022\017\n\007s" +
      "uccess\030\001 \001(\0102\211\001\n\rSmartLighting\022:\n\013Toggle" +
      "Light\022\023.ToggleLightRequest\032\024.ToggleLight" +
      "Response\"\000\022<\n\013SetSchedule\022\023.SetScheduleR" +
      "equest\032\024.SetScheduleResponse\"\000(\001B\020\n\016com." +
      "smart_homeb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ToggleLightRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ToggleLightRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ToggleLightRequest_descriptor,
        new java.lang.String[] { "LightId", "IntendedState", });
    internal_static_ToggleLightResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ToggleLightResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ToggleLightResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_SetScheduleRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SetScheduleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SetScheduleRequest_descriptor,
        new java.lang.String[] { "LightId", "IntendedState", "ScheduleTime", });
    internal_static_SetScheduleResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SetScheduleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SetScheduleResponse_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
