// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartSecurity.proto

package com.smart_home;

public final class SmartSecurityOuterClass {
  private SmartSecurityOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ArmSystemRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ArmSystemRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string security_code = 1;</code>
     */
    java.lang.String getSecurityCode();
    /**
     * <code>string security_code = 1;</code>
     */
    com.google.protobuf.ByteString
        getSecurityCodeBytes();

    /**
     * <code>string user_id = 2;</code>
     */
    java.lang.String getUserId();
    /**
     * <code>string user_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();
  }
  /**
   * <pre>
   * Message to request arming the system
   * </pre>
   *
   * Protobuf type {@code ArmSystemRequest}
   */
  public  static final class ArmSystemRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ArmSystemRequest)
      ArmSystemRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ArmSystemRequest.newBuilder() to construct.
    private ArmSystemRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ArmSystemRequest() {
      securityCode_ = "";
      userId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ArmSystemRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              securityCode_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.smart_home.SmartSecurityOuterClass.internal_static_ArmSystemRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.smart_home.SmartSecurityOuterClass.internal_static_ArmSystemRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.smart_home.SmartSecurityOuterClass.ArmSystemRequest.class, com.smart_home.SmartSecurityOuterClass.ArmSystemRequest.Builder.class);
    }

    public static final int SECURITY_CODE_FIELD_NUMBER = 1;
    private volatile java.lang.Object securityCode_;
    /**
     * <code>string security_code = 1;</code>
     */
    public java.lang.String getSecurityCode() {
      java.lang.Object ref = securityCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        securityCode_ = s;
        return s;
      }
    }
    /**
     * <code>string security_code = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSecurityCodeBytes() {
      java.lang.Object ref = securityCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        securityCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object userId_;
    /**
     * <code>string user_id = 2;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>string user_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSecurityCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, securityCode_);
      }
      if (!getUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSecurityCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, securityCode_);
      }
      if (!getUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.smart_home.SmartSecurityOuterClass.ArmSystemRequest)) {
        return super.equals(obj);
      }
      com.smart_home.SmartSecurityOuterClass.ArmSystemRequest other = (com.smart_home.SmartSecurityOuterClass.ArmSystemRequest) obj;

      boolean result = true;
      result = result && getSecurityCode()
          .equals(other.getSecurityCode());
      result = result && getUserId()
          .equals(other.getUserId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SECURITY_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getSecurityCode().hashCode();
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.smart_home.SmartSecurityOuterClass.ArmSystemRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smart_home.SmartSecurityOuterClass.ArmSystemRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smart_home.SmartSecurityOuterClass.ArmSystemRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smart_home.SmartSecurityOuterClass.ArmSystemRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smart_home.SmartSecurityOuterClass.ArmSystemRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smart_home.SmartSecurityOuterClass.ArmSystemRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smart_home.SmartSecurityOuterClass.ArmSystemRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.smart_home.SmartSecurityOuterClass.ArmSystemRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.smart_home.SmartSecurityOuterClass.ArmSystemRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.smart_home.SmartSecurityOuterClass.ArmSystemRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.smart_home.SmartSecurityOuterClass.ArmSystemRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.smart_home.SmartSecurityOuterClass.ArmSystemRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.smart_home.SmartSecurityOuterClass.ArmSystemRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Message to request arming the system
     * </pre>
     *
     * Protobuf type {@code ArmSystemRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ArmSystemRequest)
        com.smart_home.SmartSecurityOuterClass.ArmSystemRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.smart_home.SmartSecurityOuterClass.internal_static_ArmSystemRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.smart_home.SmartSecurityOuterClass.internal_static_ArmSystemRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.smart_home.SmartSecurityOuterClass.ArmSystemRequest.class, com.smart_home.SmartSecurityOuterClass.ArmSystemRequest.Builder.class);
      }

      // Construct using com.smart_home.SmartSecurityOuterClass.ArmSystemRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        securityCode_ = "";

        userId_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.smart_home.SmartSecurityOuterClass.internal_static_ArmSystemRequest_descriptor;
      }

      @java.lang.Override
      public com.smart_home.SmartSecurityOuterClass.ArmSystemRequest getDefaultInstanceForType() {
        return com.smart_home.SmartSecurityOuterClass.ArmSystemRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.smart_home.SmartSecurityOuterClass.ArmSystemRequest build() {
        com.smart_home.SmartSecurityOuterClass.ArmSystemRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.smart_home.SmartSecurityOuterClass.ArmSystemRequest buildPartial() {
        com.smart_home.SmartSecurityOuterClass.ArmSystemRequest result = new com.smart_home.SmartSecurityOuterClass.ArmSystemRequest(this);
        result.securityCode_ = securityCode_;
        result.userId_ = userId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.smart_home.SmartSecurityOuterClass.ArmSystemRequest) {
          return mergeFrom((com.smart_home.SmartSecurityOuterClass.ArmSystemRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.smart_home.SmartSecurityOuterClass.ArmSystemRequest other) {
        if (other == com.smart_home.SmartSecurityOuterClass.ArmSystemRequest.getDefaultInstance()) return this;
        if (!other.getSecurityCode().isEmpty()) {
          securityCode_ = other.securityCode_;
          onChanged();
        }
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.smart_home.SmartSecurityOuterClass.ArmSystemRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.smart_home.SmartSecurityOuterClass.ArmSystemRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object securityCode_ = "";
      /**
       * <code>string security_code = 1;</code>
       */
      public java.lang.String getSecurityCode() {
        java.lang.Object ref = securityCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          securityCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string security_code = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSecurityCodeBytes() {
        java.lang.Object ref = securityCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          securityCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string security_code = 1;</code>
       */
      public Builder setSecurityCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        securityCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string security_code = 1;</code>
       */
      public Builder clearSecurityCode() {
        
        securityCode_ = getDefaultInstance().getSecurityCode();
        onChanged();
        return this;
      }
      /**
       * <code>string security_code = 1;</code>
       */
      public Builder setSecurityCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        securityCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userId_ = "";
      /**
       * <code>string user_id = 2;</code>
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string user_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user_id = 2;</code>
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string user_id = 2;</code>
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>string user_id = 2;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ArmSystemRequest)
    }

    // @@protoc_insertion_point(class_scope:ArmSystemRequest)
    private static final com.smart_home.SmartSecurityOuterClass.ArmSystemRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.smart_home.SmartSecurityOuterClass.ArmSystemRequest();
    }

    public static com.smart_home.SmartSecurityOuterClass.ArmSystemRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ArmSystemRequest>
        PARSER = new com.google.protobuf.AbstractParser<ArmSystemRequest>() {
      @java.lang.Override
      public ArmSystemRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ArmSystemRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ArmSystemRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ArmSystemRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.smart_home.SmartSecurityOuterClass.ArmSystemRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ArmSystemResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ArmSystemResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool success = 1;</code>
     */
    boolean getSuccess();
  }
  /**
   * <pre>
   * Response message for arming the system
   * </pre>
   *
   * Protobuf type {@code ArmSystemResponse}
   */
  public  static final class ArmSystemResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ArmSystemResponse)
      ArmSystemResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ArmSystemResponse.newBuilder() to construct.
    private ArmSystemResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ArmSystemResponse() {
      success_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ArmSystemResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              success_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.smart_home.SmartSecurityOuterClass.internal_static_ArmSystemResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.smart_home.SmartSecurityOuterClass.internal_static_ArmSystemResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.smart_home.SmartSecurityOuterClass.ArmSystemResponse.class, com.smart_home.SmartSecurityOuterClass.ArmSystemResponse.Builder.class);
    }

    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>bool success = 1;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (success_ != false) {
        output.writeBool(1, success_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.smart_home.SmartSecurityOuterClass.ArmSystemResponse)) {
        return super.equals(obj);
      }
      com.smart_home.SmartSecurityOuterClass.ArmSystemResponse other = (com.smart_home.SmartSecurityOuterClass.ArmSystemResponse) obj;

      boolean result = true;
      result = result && (getSuccess()
          == other.getSuccess());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.smart_home.SmartSecurityOuterClass.ArmSystemResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smart_home.SmartSecurityOuterClass.ArmSystemResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smart_home.SmartSecurityOuterClass.ArmSystemResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smart_home.SmartSecurityOuterClass.ArmSystemResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smart_home.SmartSecurityOuterClass.ArmSystemResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smart_home.SmartSecurityOuterClass.ArmSystemResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smart_home.SmartSecurityOuterClass.ArmSystemResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.smart_home.SmartSecurityOuterClass.ArmSystemResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.smart_home.SmartSecurityOuterClass.ArmSystemResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.smart_home.SmartSecurityOuterClass.ArmSystemResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.smart_home.SmartSecurityOuterClass.ArmSystemResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.smart_home.SmartSecurityOuterClass.ArmSystemResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.smart_home.SmartSecurityOuterClass.ArmSystemResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Response message for arming the system
     * </pre>
     *
     * Protobuf type {@code ArmSystemResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ArmSystemResponse)
        com.smart_home.SmartSecurityOuterClass.ArmSystemResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.smart_home.SmartSecurityOuterClass.internal_static_ArmSystemResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.smart_home.SmartSecurityOuterClass.internal_static_ArmSystemResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.smart_home.SmartSecurityOuterClass.ArmSystemResponse.class, com.smart_home.SmartSecurityOuterClass.ArmSystemResponse.Builder.class);
      }

      // Construct using com.smart_home.SmartSecurityOuterClass.ArmSystemResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        success_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.smart_home.SmartSecurityOuterClass.internal_static_ArmSystemResponse_descriptor;
      }

      @java.lang.Override
      public com.smart_home.SmartSecurityOuterClass.ArmSystemResponse getDefaultInstanceForType() {
        return com.smart_home.SmartSecurityOuterClass.ArmSystemResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.smart_home.SmartSecurityOuterClass.ArmSystemResponse build() {
        com.smart_home.SmartSecurityOuterClass.ArmSystemResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.smart_home.SmartSecurityOuterClass.ArmSystemResponse buildPartial() {
        com.smart_home.SmartSecurityOuterClass.ArmSystemResponse result = new com.smart_home.SmartSecurityOuterClass.ArmSystemResponse(this);
        result.success_ = success_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.smart_home.SmartSecurityOuterClass.ArmSystemResponse) {
          return mergeFrom((com.smart_home.SmartSecurityOuterClass.ArmSystemResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.smart_home.SmartSecurityOuterClass.ArmSystemResponse other) {
        if (other == com.smart_home.SmartSecurityOuterClass.ArmSystemResponse.getDefaultInstance()) return this;
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.smart_home.SmartSecurityOuterClass.ArmSystemResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.smart_home.SmartSecurityOuterClass.ArmSystemResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean success_ ;
      /**
       * <code>bool success = 1;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>bool success = 1;</code>
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool success = 1;</code>
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ArmSystemResponse)
    }

    // @@protoc_insertion_point(class_scope:ArmSystemResponse)
    private static final com.smart_home.SmartSecurityOuterClass.ArmSystemResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.smart_home.SmartSecurityOuterClass.ArmSystemResponse();
    }

    public static com.smart_home.SmartSecurityOuterClass.ArmSystemResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ArmSystemResponse>
        PARSER = new com.google.protobuf.AbstractParser<ArmSystemResponse>() {
      @java.lang.Override
      public ArmSystemResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ArmSystemResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ArmSystemResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ArmSystemResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.smart_home.SmartSecurityOuterClass.ArmSystemResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetSensorStatusRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetSensorStatusRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string sensor_id = 1;</code>
     */
    java.lang.String getSensorId();
    /**
     * <code>string sensor_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getSensorIdBytes();
  }
  /**
   * <pre>
   * Message to request the status of a sensor
   * </pre>
   *
   * Protobuf type {@code GetSensorStatusRequest}
   */
  public  static final class GetSensorStatusRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetSensorStatusRequest)
      GetSensorStatusRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetSensorStatusRequest.newBuilder() to construct.
    private GetSensorStatusRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetSensorStatusRequest() {
      sensorId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetSensorStatusRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              sensorId_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.smart_home.SmartSecurityOuterClass.internal_static_GetSensorStatusRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.smart_home.SmartSecurityOuterClass.internal_static_GetSensorStatusRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.smart_home.SmartSecurityOuterClass.GetSensorStatusRequest.class, com.smart_home.SmartSecurityOuterClass.GetSensorStatusRequest.Builder.class);
    }

    public static final int SENSOR_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object sensorId_;
    /**
     * <code>string sensor_id = 1;</code>
     */
    public java.lang.String getSensorId() {
      java.lang.Object ref = sensorId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sensorId_ = s;
        return s;
      }
    }
    /**
     * <code>string sensor_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSensorIdBytes() {
      java.lang.Object ref = sensorId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sensorId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSensorIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sensorId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSensorIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sensorId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.smart_home.SmartSecurityOuterClass.GetSensorStatusRequest)) {
        return super.equals(obj);
      }
      com.smart_home.SmartSecurityOuterClass.GetSensorStatusRequest other = (com.smart_home.SmartSecurityOuterClass.GetSensorStatusRequest) obj;

      boolean result = true;
      result = result && getSensorId()
          .equals(other.getSensorId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SENSOR_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSensorId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.smart_home.SmartSecurityOuterClass.GetSensorStatusRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smart_home.SmartSecurityOuterClass.GetSensorStatusRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smart_home.SmartSecurityOuterClass.GetSensorStatusRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smart_home.SmartSecurityOuterClass.GetSensorStatusRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smart_home.SmartSecurityOuterClass.GetSensorStatusRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smart_home.SmartSecurityOuterClass.GetSensorStatusRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smart_home.SmartSecurityOuterClass.GetSensorStatusRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.smart_home.SmartSecurityOuterClass.GetSensorStatusRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.smart_home.SmartSecurityOuterClass.GetSensorStatusRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.smart_home.SmartSecurityOuterClass.GetSensorStatusRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.smart_home.SmartSecurityOuterClass.GetSensorStatusRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.smart_home.SmartSecurityOuterClass.GetSensorStatusRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.smart_home.SmartSecurityOuterClass.GetSensorStatusRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Message to request the status of a sensor
     * </pre>
     *
     * Protobuf type {@code GetSensorStatusRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetSensorStatusRequest)
        com.smart_home.SmartSecurityOuterClass.GetSensorStatusRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.smart_home.SmartSecurityOuterClass.internal_static_GetSensorStatusRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.smart_home.SmartSecurityOuterClass.internal_static_GetSensorStatusRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.smart_home.SmartSecurityOuterClass.GetSensorStatusRequest.class, com.smart_home.SmartSecurityOuterClass.GetSensorStatusRequest.Builder.class);
      }

      // Construct using com.smart_home.SmartSecurityOuterClass.GetSensorStatusRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sensorId_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.smart_home.SmartSecurityOuterClass.internal_static_GetSensorStatusRequest_descriptor;
      }

      @java.lang.Override
      public com.smart_home.SmartSecurityOuterClass.GetSensorStatusRequest getDefaultInstanceForType() {
        return com.smart_home.SmartSecurityOuterClass.GetSensorStatusRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.smart_home.SmartSecurityOuterClass.GetSensorStatusRequest build() {
        com.smart_home.SmartSecurityOuterClass.GetSensorStatusRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.smart_home.SmartSecurityOuterClass.GetSensorStatusRequest buildPartial() {
        com.smart_home.SmartSecurityOuterClass.GetSensorStatusRequest result = new com.smart_home.SmartSecurityOuterClass.GetSensorStatusRequest(this);
        result.sensorId_ = sensorId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.smart_home.SmartSecurityOuterClass.GetSensorStatusRequest) {
          return mergeFrom((com.smart_home.SmartSecurityOuterClass.GetSensorStatusRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.smart_home.SmartSecurityOuterClass.GetSensorStatusRequest other) {
        if (other == com.smart_home.SmartSecurityOuterClass.GetSensorStatusRequest.getDefaultInstance()) return this;
        if (!other.getSensorId().isEmpty()) {
          sensorId_ = other.sensorId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.smart_home.SmartSecurityOuterClass.GetSensorStatusRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.smart_home.SmartSecurityOuterClass.GetSensorStatusRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object sensorId_ = "";
      /**
       * <code>string sensor_id = 1;</code>
       */
      public java.lang.String getSensorId() {
        java.lang.Object ref = sensorId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sensorId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sensor_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSensorIdBytes() {
        java.lang.Object ref = sensorId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sensorId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sensor_id = 1;</code>
       */
      public Builder setSensorId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sensorId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sensor_id = 1;</code>
       */
      public Builder clearSensorId() {
        
        sensorId_ = getDefaultInstance().getSensorId();
        onChanged();
        return this;
      }
      /**
       * <code>string sensor_id = 1;</code>
       */
      public Builder setSensorIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sensorId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GetSensorStatusRequest)
    }

    // @@protoc_insertion_point(class_scope:GetSensorStatusRequest)
    private static final com.smart_home.SmartSecurityOuterClass.GetSensorStatusRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.smart_home.SmartSecurityOuterClass.GetSensorStatusRequest();
    }

    public static com.smart_home.SmartSecurityOuterClass.GetSensorStatusRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetSensorStatusRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetSensorStatusRequest>() {
      @java.lang.Override
      public GetSensorStatusRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetSensorStatusRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetSensorStatusRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetSensorStatusRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.smart_home.SmartSecurityOuterClass.GetSensorStatusRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetSensorStatusResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetSensorStatusResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string sensor_id = 1;</code>
     */
    java.lang.String getSensorId();
    /**
     * <code>string sensor_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getSensorIdBytes();

    /**
     * <code>bool sensor_status = 2;</code>
     */
    boolean getSensorStatus();
  }
  /**
   * <pre>
   * Response message for getting the status of a sensor
   * </pre>
   *
   * Protobuf type {@code GetSensorStatusResponse}
   */
  public  static final class GetSensorStatusResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetSensorStatusResponse)
      GetSensorStatusResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetSensorStatusResponse.newBuilder() to construct.
    private GetSensorStatusResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetSensorStatusResponse() {
      sensorId_ = "";
      sensorStatus_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetSensorStatusResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              sensorId_ = s;
              break;
            }
            case 16: {

              sensorStatus_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.smart_home.SmartSecurityOuterClass.internal_static_GetSensorStatusResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.smart_home.SmartSecurityOuterClass.internal_static_GetSensorStatusResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.smart_home.SmartSecurityOuterClass.GetSensorStatusResponse.class, com.smart_home.SmartSecurityOuterClass.GetSensorStatusResponse.Builder.class);
    }

    public static final int SENSOR_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object sensorId_;
    /**
     * <code>string sensor_id = 1;</code>
     */
    public java.lang.String getSensorId() {
      java.lang.Object ref = sensorId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sensorId_ = s;
        return s;
      }
    }
    /**
     * <code>string sensor_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSensorIdBytes() {
      java.lang.Object ref = sensorId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sensorId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENSOR_STATUS_FIELD_NUMBER = 2;
    private boolean sensorStatus_;
    /**
     * <code>bool sensor_status = 2;</code>
     */
    public boolean getSensorStatus() {
      return sensorStatus_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSensorIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sensorId_);
      }
      if (sensorStatus_ != false) {
        output.writeBool(2, sensorStatus_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSensorIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sensorId_);
      }
      if (sensorStatus_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, sensorStatus_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.smart_home.SmartSecurityOuterClass.GetSensorStatusResponse)) {
        return super.equals(obj);
      }
      com.smart_home.SmartSecurityOuterClass.GetSensorStatusResponse other = (com.smart_home.SmartSecurityOuterClass.GetSensorStatusResponse) obj;

      boolean result = true;
      result = result && getSensorId()
          .equals(other.getSensorId());
      result = result && (getSensorStatus()
          == other.getSensorStatus());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SENSOR_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSensorId().hashCode();
      hash = (37 * hash) + SENSOR_STATUS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSensorStatus());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.smart_home.SmartSecurityOuterClass.GetSensorStatusResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smart_home.SmartSecurityOuterClass.GetSensorStatusResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smart_home.SmartSecurityOuterClass.GetSensorStatusResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smart_home.SmartSecurityOuterClass.GetSensorStatusResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smart_home.SmartSecurityOuterClass.GetSensorStatusResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smart_home.SmartSecurityOuterClass.GetSensorStatusResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smart_home.SmartSecurityOuterClass.GetSensorStatusResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.smart_home.SmartSecurityOuterClass.GetSensorStatusResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.smart_home.SmartSecurityOuterClass.GetSensorStatusResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.smart_home.SmartSecurityOuterClass.GetSensorStatusResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.smart_home.SmartSecurityOuterClass.GetSensorStatusResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.smart_home.SmartSecurityOuterClass.GetSensorStatusResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.smart_home.SmartSecurityOuterClass.GetSensorStatusResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Response message for getting the status of a sensor
     * </pre>
     *
     * Protobuf type {@code GetSensorStatusResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetSensorStatusResponse)
        com.smart_home.SmartSecurityOuterClass.GetSensorStatusResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.smart_home.SmartSecurityOuterClass.internal_static_GetSensorStatusResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.smart_home.SmartSecurityOuterClass.internal_static_GetSensorStatusResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.smart_home.SmartSecurityOuterClass.GetSensorStatusResponse.class, com.smart_home.SmartSecurityOuterClass.GetSensorStatusResponse.Builder.class);
      }

      // Construct using com.smart_home.SmartSecurityOuterClass.GetSensorStatusResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sensorId_ = "";

        sensorStatus_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.smart_home.SmartSecurityOuterClass.internal_static_GetSensorStatusResponse_descriptor;
      }

      @java.lang.Override
      public com.smart_home.SmartSecurityOuterClass.GetSensorStatusResponse getDefaultInstanceForType() {
        return com.smart_home.SmartSecurityOuterClass.GetSensorStatusResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.smart_home.SmartSecurityOuterClass.GetSensorStatusResponse build() {
        com.smart_home.SmartSecurityOuterClass.GetSensorStatusResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.smart_home.SmartSecurityOuterClass.GetSensorStatusResponse buildPartial() {
        com.smart_home.SmartSecurityOuterClass.GetSensorStatusResponse result = new com.smart_home.SmartSecurityOuterClass.GetSensorStatusResponse(this);
        result.sensorId_ = sensorId_;
        result.sensorStatus_ = sensorStatus_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.smart_home.SmartSecurityOuterClass.GetSensorStatusResponse) {
          return mergeFrom((com.smart_home.SmartSecurityOuterClass.GetSensorStatusResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.smart_home.SmartSecurityOuterClass.GetSensorStatusResponse other) {
        if (other == com.smart_home.SmartSecurityOuterClass.GetSensorStatusResponse.getDefaultInstance()) return this;
        if (!other.getSensorId().isEmpty()) {
          sensorId_ = other.sensorId_;
          onChanged();
        }
        if (other.getSensorStatus() != false) {
          setSensorStatus(other.getSensorStatus());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.smart_home.SmartSecurityOuterClass.GetSensorStatusResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.smart_home.SmartSecurityOuterClass.GetSensorStatusResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object sensorId_ = "";
      /**
       * <code>string sensor_id = 1;</code>
       */
      public java.lang.String getSensorId() {
        java.lang.Object ref = sensorId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sensorId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sensor_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSensorIdBytes() {
        java.lang.Object ref = sensorId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sensorId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sensor_id = 1;</code>
       */
      public Builder setSensorId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sensorId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sensor_id = 1;</code>
       */
      public Builder clearSensorId() {
        
        sensorId_ = getDefaultInstance().getSensorId();
        onChanged();
        return this;
      }
      /**
       * <code>string sensor_id = 1;</code>
       */
      public Builder setSensorIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sensorId_ = value;
        onChanged();
        return this;
      }

      private boolean sensorStatus_ ;
      /**
       * <code>bool sensor_status = 2;</code>
       */
      public boolean getSensorStatus() {
        return sensorStatus_;
      }
      /**
       * <code>bool sensor_status = 2;</code>
       */
      public Builder setSensorStatus(boolean value) {
        
        sensorStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool sensor_status = 2;</code>
       */
      public Builder clearSensorStatus() {
        
        sensorStatus_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GetSensorStatusResponse)
    }

    // @@protoc_insertion_point(class_scope:GetSensorStatusResponse)
    private static final com.smart_home.SmartSecurityOuterClass.GetSensorStatusResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.smart_home.SmartSecurityOuterClass.GetSensorStatusResponse();
    }

    public static com.smart_home.SmartSecurityOuterClass.GetSensorStatusResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetSensorStatusResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetSensorStatusResponse>() {
      @java.lang.Override
      public GetSensorStatusResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetSensorStatusResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetSensorStatusResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetSensorStatusResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.smart_home.SmartSecurityOuterClass.GetSensorStatusResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ArmSystemRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ArmSystemRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ArmSystemResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ArmSystemResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetSensorStatusRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetSensorStatusRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetSensorStatusResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetSensorStatusResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023smartSecurity.proto\":\n\020ArmSystemReques" +
      "t\022\025\n\rsecurity_code\030\001 \001(\t\022\017\n\007user_id\030\002 \001(" +
      "\t\"$\n\021ArmSystemResponse\022\017\n\007success\030\001 \001(\010\"" +
      "+\n\026GetSensorStatusRequest\022\021\n\tsensor_id\030\001" +
      " \001(\t\"C\n\027GetSensorStatusResponse\022\021\n\tsenso" +
      "r_id\030\001 \001(\t\022\025\n\rsensor_status\030\002 \001(\0102\215\001\n\rSm" +
      "artSecurity\0224\n\tArmSystem\022\021.ArmSystemRequ" +
      "est\032\022.ArmSystemResponse\"\000\022F\n\017GetSensorSt" +
      "atus\022\027.GetSensorStatusRequest\032\030.GetSenso" +
      "rStatusResponse\"\000B\020\n\016com.smart_homeb\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ArmSystemRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ArmSystemRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ArmSystemRequest_descriptor,
        new java.lang.String[] { "SecurityCode", "UserId", });
    internal_static_ArmSystemResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ArmSystemResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ArmSystemResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_GetSensorStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GetSensorStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetSensorStatusRequest_descriptor,
        new java.lang.String[] { "SensorId", });
    internal_static_GetSensorStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GetSensorStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetSensorStatusResponse_descriptor,
        new java.lang.String[] { "SensorId", "SensorStatus", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
